### ISSUE TITLE
openapi[12.0-13.0] error while trying to get date fields

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/sync-addons#131]
Using demo data I tried to get model's fields with this request:

`curl -X PATCH "http://example.com/api/v1/demo/res.partner/call/search_read" -H "accept: application/json" \
-H "authorization: Basic b3BlbmFwaTpiNmQ1NDA1YS0zMWU3LTQ3MjEtYTQyOC0xMmU1OTYzMTYyYzY=" -H "Content-Type: application/json" \
-d "{ \"args\": [[[\"is_company\", \"=\", \"True\" ]]]}"`
 
And got this:
```
Traceback (most recent call last):
  File "/mnt/addons/sync-addons/openapi/controllers/pinguin.py", line 112, in successful_response
    response = json.dumps(data.ids)
AttributeError: 'list' object has no attribute 'ids'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/addons/sync-addons/openapi/controllers/pinguin.py", line 369, in controller_method_wrapper
    response = controller_method(*iargs, **ikwargs)
  File "/mnt/addons/sync-addons/openapi/controllers/api.py", line 203, in call_method_multi__PATCH
    success_code=pinguin.CODE__success,
  File "/mnt/addons/sync-addons/openapi/controllers/pinguin.py", line 691, in wrap__resource__call_method
    return successful_response(success_code, data=results)
  File "/mnt/addons/sync-addons/openapi/controllers/pinguin.py", line 114, in successful_response
    response = json.dumps(data) if data else None
  File "/usr/local/lib/python3.7/dist-packages/simplejson/__init__.py", line 395, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/dist-packages/simplejson/encoder.py", line 298, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.7/dist-packages/simplejson/encoder.py", line 684, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/local/lib/python3.7/dist-packages/simplejson/encoder.py", line 531, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/lib/python3.7/dist-packages/simplejson/encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python3.7/dist-packages/simplejson/encoder.py", line 716, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.7/dist-packages/simplejson/encoder.py", line 273, in default
    o.class.name)
TypeError: Object of type datetime is not JSON serializable
```

This error occurs due to the fact that since odoo 12.0 datetime fields have ceased to be strings

need to fix somewhere here:
12.0: https://github.com/itpp-labs/sync-addons/blob/12.0/openapi/controllers/pinguin.py#L1045-L1064

13.0: https://github.com/itpp-labs/sync-addons/blob/13.0/base_api/lib/pinguin.py#L326-L348

**Comment by trojikman** [comment]
Found this: 
https://github.com/itpp-labs/sync-addons/blob/373652567d3d5d07deec602b9cd2775934562d12/openapi/controllers/apijsonrequest.py#L91-L93 
probably the root of the problem here
