### ISSUE TITLE
OpenAPI: 500 Internal Server Error server error response code in case of Log request = Short

### ISSUE THREAD

**Issue by Ramil-Mukhametzyanov** [itpp-labs/sync-addons#168]
OpenAPI 13.0.1.2.1
Log Requests = Short

curl -X PATCH "http://demo.server.info/api/v1/demo/res.partner/call/search_read_nested" -H  "accept: application/json" -H  "authorization: Basic YWRtaW46YTg2NTQwYzYtYWMyZC00NzVhLTgyNzYtNzFhY2MxMTUzYjQ5" -H  "Content-Type: application/json" -d "{  \"args\": [[[\"id\", \">\", \"0\"]],    [      \"name\",\"id\"    ]  ]}"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

2020-09-16 07:29:41,182 13 ERROR demo odoo.addons.openapi.controllers.apijsonrequest: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 108, in _handle_exception
    return super(ApiJsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 159, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 200, in response_wrap
    response = f(*args, **kw)
  File "/mnt/extra-addons/openapi/controllers/pinguin.py", line 386, in controller_method_wrapper
    create_log_record(**data_for_log)
  File "/mnt/extra-addons/openapi/controllers/pinguin.py", line 284, in create_log_record
    _create_log_record(env, **kwargs)
  File "/mnt/extra-addons/openapi/controllers/pinguin.py", line 323, in _create_log_record
    del log_data["request_data"][k]
KeyError: 'form'
2020-09-16 07:29:41,184 13 ERROR demo odoo.addons.openapi.controllers.apijsonrequest: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 108, in _handle_exception
    return super(ApiJsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 159, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 200, in response_wrap
    response = f(*args, **kw)
  File "/mnt/extra-addons/openapi/controllers/pinguin.py", line 386, in controller_method_wrapper
    create_log_record(**data_for_log)
  File "/mnt/extra-addons/openapi/controllers/pinguin.py", line 284, in create_log_record
    _create_log_record(env, **kwargs)
  File "/mnt/extra-addons/openapi/controllers/pinguin.py", line 323, in _create_log_record
    del log_data["request_data"][k]
KeyError: 'form'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 108, in _handle_exception
    return super(ApiJsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 181, in dispatch
    return self._handle_exception(e)
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 121, in _handle_exception
    "code": exception.response.status_code,
AttributeError: 'KeyError' object has no attribute 'response'
2020-09-16 07:29:41,191 13 INFO demo werkzeug: 172.17.0.1 - - [16/Sep/2020 07:29:41] "PATCH /api/v1/demo/res.partner/call/search_read_nested HTTP/1.0" 500 - 28 0.043 0.067
2020-09-16 07:29:41,198 13 ERROR demo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1457, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 233, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 201, in _handle_exception
    return request._handle_exception(exception)
  File "/mnt/extra-addons/openapi/controllers/apijsonrequest.py", line 121, in _handle_exception
    "code": exception.response.status_code,
AttributeError: 'AttributeError' object has no attribute 'response' - - -
2

**Comment by yelizariev** [comment]
Thanks for report. 

This should fix it: https://github.com/itpp-labs/sync-addons/pull/174

@trojikman could you please check in other version and apply the fix properly (i.e. with updating module version)
