### ISSUE TITLE
Sync: ValueError: Compute method failed to assign sync.trigger.webhook

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/sync-addons#242]
Steps to reproduce:

1. Go to `Sync Projects`
2. Create a new one
3. Go to `Available Tasks` tab and Add a line
4. Go to `Avalable Triggers` tab 
5. In `Webhooks` section add a new line and get the following error:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1377, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6242, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6047, in __init__
    self.fetch(name)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6057, in fetch
    self[name] = record[name]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5664, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1024, in __get__
    raise ValueError("Compute method failed to assign %s.%s" % (record, self.name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Compute method failed to assign sync.trigger.webhook(<NewId 0x7f1ab22040f0>,).website_url
```
Affected versions: the error experienced in 14.0 but we need previous versions after fixing it in 14.0

**Comment by trojikman** [comment]
It is fixed in v14, but we need to check this behavior in previous versions

**Comment by mentalko** [comment]
я помнится уже перенес этот комит в 13 и 12, проверю работу

**Comment by trojikman** [comment]
> я помнится уже перенес этот комит в 13 и 12, проверю работу

Здесь бы, вероятно, отобразилось, потому что в коммите ссылка на ишью. Если ошибка будет, то перенеси, пожалуйста

**Comment by mentalko** [comment]
перепутал, это был другой коммит

**Comment by mentalko** [comment]
v13 что с фиксом что без него такая ошибка

![Screenshot from 2021-07-13 19-49-04](https://user-images.githubusercontent.com/55297626/125431222-cc8b6ee5-d101-4389-a464-1a1446747636.png)

**Comment by yelizariev** [comment]
@mentalko заведи новое дело (ишью) и напиши шаги воспроизведения
