### ISSUE TITLE
Error installing the openapi odoo module

### ISSUE THREAD

**Issue by carlo-github** [itpp-labs/sync-addons#460]
I would like to use the module openapi in odoo.sh, but I have an error.
Please let me know what is missing in this steps.

- I follow your instruction for doing it (https://apps.odoo.com/apps/modules/16.0/openapi/), so before adding the module in git I launched from the shell the command:

python3 -m pip install bravado_core swagger_spec_validator

- And to be sure I executed twice with this result:

odooins-v-m-main-db1 [dev/16.0]:~$ python3 -m pip install bravado_core swagger_spec_validator
Defaulting to user installation because normal site-packages is not writeable
Collecting bravado_core
  Downloading bravado_core-5.17.1-py2.py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.7/67.7 kB 2.1 MB/s eta 0:00:00
Collecting swagger_spec_validator
  Downloading swagger_spec_validator-3.0.3-py2.py3-none-any.whl (27 kB)
Collecting jsonref (from bravado_core)
  Downloading jsonref-1.1.0-py3-none-any.whl (9.4 kB)
Collecting jsonschema[format]>=2.5.1 (from bravado_core)
  Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 kB 8.3 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from bravado_core) (2.8.1)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from bravado_core) (5.4.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from bravado_core) (2.25.1)
Requirement already satisfied: simplejson in /usr/lib/python3/dist-packages (from bravado_core) (3.17.6)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from bravado_core) (1.16.0)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from bravado_core) (2022.1)
Requirement already satisfied: msgpack>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from bravado_core) (1.0.4)
Collecting typing-extensions (from swagger_spec_validator)
  Downloading typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3/dist-packages (from jsonschema[format]>=2.5.1->bravado_core) (21.2.0)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema[format]>=2.5.1->bravado_core)
  Downloading pyrsistent-0.19.3-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 9.3 MB/s eta 0:00:00
Collecting fqdn (from jsonschema[format]>=2.5.1->bravado_core)
  Downloading fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from jsonschema[format]>=2.5.1->bravado_core) (3.3)
Collecting isoduration (from jsonschema[format]>=2.5.1->bravado_core)
  Downloading isoduration-20.11.0-py3-none-any.whl (11 kB)
Collecting jsonpointer>1.13 (from jsonschema[format]>=2.5.1->bravado_core)
  Downloading jsonpointer-2.4-py2.py3-none-any.whl (7.8 kB)
Collecting rfc3339-validator (from jsonschema[format]>=2.5.1->bravado_core)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl (3.5 kB)
Collecting rfc3987 (from jsonschema[format]>=2.5.1->bravado_core)
  Downloading rfc3987-1.3.8-py2.py3-none-any.whl (13 kB)
Collecting uri-template (from jsonschema[format]>=2.5.1->bravado_core)
  Downloading uri_template-1.2.0-py3-none-any.whl (10 kB)
Collecting webcolors>=1.11 (from jsonschema[format]>=2.5.1->bravado_core)
  Downloading webcolors-1.13-py3-none-any.whl (14 kB)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format]>=2.5.1->bravado_core)
  Downloading arrow-1.2.3-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 7.5 MB/s eta 0:00:00
Installing collected packages: rfc3987, webcolors, uri-template, typing-extensions, rfc3339-validator, pyrsistent, jsonref, jsonpointer, fqdn, arrow, jsonschema, isoduration, swagger_spec_validator, bravado_core
  WARNING: The script jsonschema is installed in '/home/odoo/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
Successfully installed arrow-1.2.3 bravado_core-5.17.1 fqdn-1.5.1 isoduration-20.11.0 jsonpointer-2.4 jsonref-1.1.0 jsonschema-4.17.3 pyrsistent-0.19.3 rfc3339-validator-0.1.4 rfc3987-1.3.8 swagger_spec_validator-3.0.3 typing-extensions-4.6.3 uri-template-1.2.0 webcolors-1.13
 
odooins-v-m-main-db1 [dev/16.0]:~ $ python3 -m pip install bravado_core swagger_spec_validator
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bravado_core in ./.local/lib/python3.10/site-packages (5.17.1)
Requirement already satisfied: swagger_spec_validator in ./.local/lib/python3.10/site-packages (3.0.3)
Requirement already satisfied: jsonref in ./.local/lib/python3.10/site-packages (from bravado_core) (1.1.0)
Requirement already satisfied: jsonschema[format]>=2.5.1 in ./.local/lib/python3.10/site-packages (from bravado_core) (4.17.3)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from bravado_core) (2.8.1)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from bravado_core) (5.4.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from bravado_core) (2.25.1)
Requirement already satisfied: simplejson in /usr/lib/python3/dist-packages (from bravado_core) (3.17.6)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from bravado_core) (1.16.0)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from bravado_core) (2022.1)
Requirement already satisfied: msgpack>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from bravado_core) (1.0.4)
Requirement already satisfied: typing-extensions in ./.local/lib/python3.10/site-packages (from swagger_spec_validator) (4.6.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3/dist-packages (from jsonschema[format]>=2.5.1->bravado_core) (21.2.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in ./.local/lib/python3.10/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (0.19.3)
Requirement already satisfied: fqdn in ./.local/lib/python3.10/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (1.5.1)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from jsonschema[format]>=2.5.1->bravado_core) (3.3)
Requirement already satisfied: isoduration in ./.local/lib/python3.10/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in ./.local/lib/python3.10/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (2.4)
Requirement already satisfied: rfc3339-validator in ./.local/lib/python3.10/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (0.1.4)
Requirement already satisfied: rfc3987 in ./.local/lib/python3.10/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (1.3.8)
Requirement already satisfied: uri-template in ./.local/lib/python3.10/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (1.2.0)
Requirement already satisfied: webcolors>=1.11 in ./.local/lib/python3.10/site-packages (from jsonschema[format]>=2.5.1->bravado_core) (1.13)
Requirement already satisfied: arrow>=0.15.0 in ./.local/lib/python3.10/site-packages (from isoduration->jsonschema[format]>=2.5.1->bravado_core) (1.2.3)
odooins-v-m-main-db1 [dev/16.0]:~$ 
 
 

- But then during the Rebuild operation I got this error:

 
2023-06-20 09:17:31,770 4 WARNING odooins-v-m-main-db1 odoo.addons.base.models.ir_module: DistributionNotFound: The 'bravado_core' distribution was not found and is required by the application
2023-06-20 09:17:31,782 4 WARNING odooins-v-m-main-db1 odoo.modules.loading: Transient module states were reset
2023-06-20 09:17:31,786 4 ERROR odooins-v-m-main-db1 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 339, in _check_python_external_dependency
    pkg_resources.get_distribution(pydep)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 471, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 347, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'bravado_core' distribution was not found and is required by the application
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 342, in _check_python_external_dependency
    importlib.import_module(pydep)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bravado_core'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 373, in check_external_dependencies
    cls._check_external_dependencies(terp)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 361, in _check_external_dependencies
    Module._check_python_external_dependency(pydep)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 347, in _check_python_external_dependency
    raise Exception('Python library not installed: %s' % (pydep,))
Exception: Python library not installed: bravado_core
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 455, in load_modules
    modules.button_install()
  File "<decorator-gen-73>", line 2, in button_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 433, in button_install
    modules._state_update('to install', ['uninstalled'])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 412, in _state_update
    self.check_external_dependencies(module.name, newstate)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 381, in check_external_dependencies
    raise UserError(msg % (module_name, e.args[0]))
odoo.exceptions.UserError: Unable to install module "openapi" because an external dependency is not met: Python library not installed: bravado_core
2023-06-20 09:17:31,791 4 CRITICAL odooins-v-m-main-db1 odoo.service.server: Failed to initialize database `odooins-v-m-main-db1`. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 339, in _check_python_external_dependency
    pkg_resources.get_distribution(pydep)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 471, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 347, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'bravado_core' distribution was not found and is required by the application
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 342, in _check_python_external_dependency
    importlib.import_module(pydep)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bravado_core'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 373, in check_external_dependencies
    cls._check_external_dependencies(terp)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 361, in _check_external_dependencies
    Module._check_python_external_dependency(pydep)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 347, in _check_python_external_dependency
    raise Exception('Python library not installed: %s' % (pydep,))
Exception: Python library not installed: bravado_core
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 455, in load_modules
    modules.button_install()
  File "<decorator-gen-73>", line 2, in button_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 433, in button_install
    modules._state_update('to install', ['uninstalled'])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 412, in _state_update
    self.check_external_dependencies(module.name, newstate)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 381, in check_external_dependencies
    raise UserError(msg % (module_name, e.args[0]))
odoo.exceptions.UserError: Unable to install module "openapi" because an external dependency is not met: Python library not installed: bravado_core

**Comment by tribalgathering** [comment]
You should add the python libraries to requirements.txt file and upload it on github repo linked to odoo.sh

**Comment by ilmir-k** [comment]
You should add the python libraries to requirements.txt file (if you don't have it yet) and upload it on github repo linked to odoo.sh project.
